@startuml

class User << Entity >> {
 - String name
 - Email email
 - Password password
 - []Skill skills
 - String profile
 - Career career
}

class Password << ValueObject >> {
 - String code
}

class Email << ValueObject >> {
 - String mailAddress
}

class Skill << Entity >> {
 - []Tag tags
 - int evaluation
 - int years
}

class Tag << ValueObject >> {
 - String name 
}

class Career << Entity >> {
 - String detail
 - int startYear
 - int endYear
}

User "1" -- "1" Email
User "1" -- "1" Password
User "1" -- "1" Career
User "1" -- "1..*" Skill
Skill "1..*" -- "1..*" Tag

@enduml
