-- MySQL Script generated by MySQL Workbench
-- Mon Jan  2 09:20:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
  `ss` INT NOT NULL,
  `table1col` VARCHAR(45) NULL,
  `df` VARCHAR(45) NULL,
  PRIMARY KEY (`ss`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
  `dadda` INT NOT NULL,
  PRIMARY KEY (`dadda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profile` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MentorRequirement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MentorRequirement` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `category` ENUM('programming', 'marketing', 'design', 'writing', 'movie', 'business', 'language', 'lifestyle') NOT NULL,
  `contact_type` ENUM('one_off', 'continuous') NOT NULL,
  `consultation_method` ENUM('chat', 'video') NOT NULL,
  `description` VARCHAR(2000) NOT NULL,
  `budget` INT NOT NULL,
  `application_period` INT NOT NULL,
  `status` ENUM('publish', 'cancel') NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MentoringProposal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MentoringProposal` (
  `id` INT NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  `mentor_requirement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mentor_requirement_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`MentorRequirement` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MentoringPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MentoringPlan` (
  `id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `category` ENUM('programming', 'marketing', 'design', 'writing', 'movie', 'business', 'language', 'lifestyle') NOT NULL,
  `content` VARCHAR(255) NOT NULL,
  `status` ENUM('publish', 'cancel') NOT NULL,
  `pricing` VARCHAR(45) NOT NULL,
  `consultation_method` ENUM('chat', 'video') NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contract`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Contract` (
  `id` INT NOT NULL,
  `mentor_id` INT NOT NULL,
  `mentee_id` INT NOT NULL,
  `mentoring_plan_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `mentor_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mentee_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mentoring_plan_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`MentoringPlan` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Career`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Career` (
  `id` INT NOT NULL,
  `detail` VARCHAR(1000) NOT NULL,
  `start_year` INT NOT NULL,
  `end_year` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Skill` (
  `id` INT NOT NULL,
  `evaluation` INT NOT NULL,
  `years` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SkillTagging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SkillTagging` (
  `id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `skill_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Skill` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tag_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`tag` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MonitoringPlanTagging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MonitoringPlanTagging` (
  `id` INT NOT NULL,
  `monitaring_plan_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `tag_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`tag` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `monitoring_plan_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`MentoringPlan` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MentorRequirementTagging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MentorRequirementTagging` (
  `id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `mentor_requirement_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `tag_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`tag` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `mentor_requirement_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`MentorRequirement` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserSkillBelonging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserSkillBelonging` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`User` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `skill_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Skill` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
