version: '3'

volumes:
  db-data:

services:
  web:
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    tty: true
    ports:
      - "8080:80"
    volumes:
      - '../src:/app/src'
    depends_on:
      - db
    environment:
      - 'DB_HOST=db'
      - 'DB_PORT=5432'
      - 'DB_USER=postgres'
      - 'DB_PASSWORD=postgres'
      - 'DB_NAME=architecture_study'
  db:
    container_name: architecture_study
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=architecture_study'
